# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Code4HealthTM
email: info@code4health.org
description: > # this means to ignore newlines until "baseurl:"
  Code4Health is an initiative supported by NHS England and NHS Digital to enable the best use of digital tools and technology to deliver safe, high quality, efficient and compassionate care
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://code4health.org" # the base hostname & protocol for your site
twitter_username: code4health
github_username:  Apperta

collections:
 - communities
 - supporters

gems:
  - jekyll-archives

# Build settings
markdown: kramdown
exclude: ["README.md"]
include: ['_pages']

jekyll-archives:
  enabled: all
  layout: 'archive'
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    category: '/category/:name/'
